# Generated by Django 4.2 on 2023-05-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
